apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2024-04-04T20:02:10Z"
  generation: 2
  labels:
    app: python-flask-docker-k8s
  name: python-flask-docker-k8s
  namespace: default
  resourceVersion: "4046"
  uid: 8e7bd3d3-13fc-440f-9faa-b3781a275720
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: python-flask-docker-k8s
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-flask-docker-k8s
    spec:
      containers:
      - image: python-flask-docker-k8s
        imagePullPolicy: Never
        name: python-flask-docker-k8s
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-04-04T20:02:10Z"
    lastUpdateTime: "2024-04-04T20:07:55Z"
    message: ReplicaSet "python-flask-docker-server-8568df57cf" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-04-05T13:55:48Z"
    lastUpdateTime: "2024-04-05T13:55:48Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
